services:
  - type: web
    name: pg-management
    runtime: docker
    repo: https://github.com/rajsojitra11/pg_management
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_NAME
        value: PG Management
      - key: APP_URL
        fromService:
          type: web
          name: pg-management
          envVarKey: RENDER_EXTERNAL_URL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: USE_LOCAL_DB
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_TIMEZONE
        value: Asia/Kolkata
      - key: COMPANY_NAME
        value: PG Management
      - key: COMPANY_ADDRESS
        value: 14/A Lohanagar, Nr. Pavagadhi Estate, B/h Passport Office, Gondal road, Rajkot
      - key: INSTALL_TYPE
        value: default

databases:
  - name: pg-management-db
    databaseName: pg_management
    user: pg_management
    plan: free
    postgresMajorVersion: 16
