services:
  - type: web
    name: pg-management
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile

    autoDeploy: true

    healthCheckPath: /up

    envVars:
      # Laravel
      - key: APP_NAME
        value: "PG Management"

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        value: "base64:DKD/5JhDEbr9BCzGmC/sUI4IArXgGL1oyJc+8skaww4="

      - key: APP_URL
        sync: false

      - key: APP_TIMEZONE
        value: Asia/Kolkata

      - key: LOG_CHANNEL
        value: stderr

      # Database
      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        value: dpg-d9if0ljtqb8s738qc0vg-a

      - key: DB_PORT
        value: "5432"

      - key: DB_DATABASE
        value: pgmanagement_db_v0f7

      - key: DB_USERNAME
        value: pgmanagement_db_v0f7_user

      - key: DB_PASSWORD
        value: hTiWCZTtTA7Gij8osbRwBWQJjVB1txmB

      - key: DB_SSLMODE
        value: require

      # Laravel Drivers
      - key: SESSION_DRIVER
        value: file

      - key: CACHE_STORE
        value: array

      - key: QUEUE_CONNECTION
        value: sync

      - key: FILESYSTEM_DISK
        value: public

      # Company
      - key: COMPANY_NAME
        value: PG Management

      - key: COMPANY_ADDRESS
        value: "14/A Lohanagar, Nr. Pavagadhi Estate, B/h Passport Office, Gondal Road, Rajkot"

      - key: INSTALL_TYPE
        value: default

      # Mail
      - key: MAIL_MAILER
        value: smtp

      - key: MAIL_HOST
        sync: false

      - key: MAIL_PORT
        sync: false

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

      - key: MAIL_ENCRYPTION
        sync: false

      - key: MAIL_FROM_ADDRESS
        sync: false

      - key: MAIL_FROM_NAME
        value: "PG Management"
