<?php

/*
 * Manifest for the APPLICATION CORE group. Each entry maps a single env var
 * to its description, type, default, criticality, and (where applicable)
 * profile-cascade reference. Read by App\Services\EnvManifest\EnvManifest.
 *
 * One file per group. Group name is the filename minus `.php`.
 */

return [
    'APP_KEY' => [
        'description' => 'Encryption key for cookies, sessions, and passwords.',
        'long' => 'Auto-generated by `php artisan key:generate`. If lost, all encrypted data becomes unreadable.',
        'type' => 'secret',
        'default' => '',
        'criticality' => 'high',
        'secret' => true,
        'business_relevant' => false,
    ],
    'APP_NAME' => [
        'description' => 'Shown in page titles, emails, and browser tabs.',
        'type' => 'string',
        'default' => 'ERP',
        'criticality' => 'low',
        'business_relevant' => false,
    ],
    'APP_ENV' => [
        'description' => 'Controls error display and config caching behavior.',
        'long' => '`local` shows detailed errors; `production` hides them. Always use `production` on live servers.',
        'type' => 'enum',
        'allowed' => ['local', 'staging', 'production', 'testing'],
        'default' => 'production',
        'criticality' => 'high',
    ],
    'APP_DEBUG' => [
        'description' => 'When true, full stack traces are shown on errors (security risk in production).',
        'type' => 'bool',
        'allowed' => [true, false, 1, 0, '1', '0', 'true', 'false'],
        'default' => false,
        'criticality' => 'high',
    ],
    'APP_URL' => [
        'description' => 'The base URL of the application (incl. https://).',
        'type' => 'url',
        'default' => 'https://example.test',
        'criticality' => 'high',
    ],
    'APP_TIMEZONE' => [
        'description' => 'Server timezone for date/time operations.',
        'type' => 'string',
        'default' => 'Asia/Kolkata',
        'criticality' => 'medium',
    ],
    'APP_LOCALE' => [
        'description' => 'Primary language used for UI labels, validation messages, and translations.',
        'type' => 'string',
        'default' => 'en',
        'criticality' => 'low',
    ],
    'APP_FALLBACK_LOCALE' => [
        'description' => 'Language used when a translation key is missing in APP_LOCALE.',
        'type' => 'string',
        'default' => 'en',
        'criticality' => 'low',
    ],
    'COMPANY_NAME' => [
        'description' => 'Displayed in the sidebar, headers, PDF exports, and email templates.',
        'type' => 'string',
        'default' => '',
        'criticality' => 'low',
    ],
    'COMPANY_ADDRESS' => [
        'description' => 'Displayed on invoices, purchase orders, and printed documents.',
        'type' => 'string',
        'default' => '',
        'criticality' => 'low',
    ],
];
